### ISSUE TITLE
ERROR in unable to locate '/app/vendure-nx/apps/worker/src/assets/**/*' glob

### ISSUE THREAD

**Issue by andermarcebr** [vendure-ecommerce/vendure-nx#1]
when I run the yarn dev:servercommand the error message appears

$ yarn dev:server
yarn run v1.22.19
$ nx run-many --target=serve --projects=server,worker

 >  NX   Running target serve for 2 project(s):

    - server
    - worker

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run server:serve

> nx run worker:serve

$ /app/vendure-nx/node_modules/.bin/tsc --project apps/server/tsconfig.migrations.json
chunk (runtime: main) main.js (main) 4.69 KiB [entry] [rendered]

ERROR in unable to locate '/app/vendure-nx/apps/worker/src/assets/**/*' glob

webpack compiled with 1 error (c82837e39422ae14)
There was an error with the build. See above.
/app/vendure-nx/dist/apps/worker/main.js was not restarted.
Type-checking in progress...

**Comment by michaelbromley** [comment]
Thanks for the report!
